### ISSUE TITLE
New Banner for shop

### ISSUE THREAD

**Issue by healthybee** [healthybee/healthybee-web#5]
As a Shopkeeper, I want to have banner so that people can see HealthyBee name and feel attraction towards it.

Acceptance criteria:-
1. It should have HealthyBee Name in bold.
2. It should have sub heating as ( Juices| Fruits | sandwiches| Snacks ).
3. It should have Mobile number :- +91 8007317771 somewhere at corner
4. It should have website address :- www.healthybee.fit

**Comment by kumarabhishek009** [comment]
[HealthyBeeLogo.pdf](https://github.com/healthybee/healthybee-web/files/1290688/HealthyBeeLogo.pdf)
There are two options. Confirm me the final one.

**Comment by kumarabhishek009** [comment]
![logo_whitebg](https://user-images.githubusercontent.com/31815433/30251703-f8d8d3a8-9682-11e7-9cc0-249efbbb3316.jpg)
check 2 more options.

**Comment by kumarabhishek009** [comment]
![1 logo_blackbg](https://user-images.githubusercontent.com/31815433/30252087-e5e08ab4-9689-11e7-9196-01930998d268.jpg)
![1 logo_whitebg](https://user-images.githubusercontent.com/31815433/30252088-e5edfe88-9689-11e7-8f8d-3a980153adf2.jpg)
![1 logo_yellowbg](https://user-images.githubusercontent.com/31815433/30252089-e60ac2ac-9689-11e7-8d33-a954ec77fcd3.jpg)
![2 logo_whitebg-1](https://user-images.githubusercontent.com/31815433/30252090-e60e5124-9689-11e7-867a-5a6fae4ce1c4.jpg)
![2 logo_whitebg](https://user-images.githubusercontent.com/31815433/30252091-e61297a2-9689-11e7-8b4b-b2876bd81201.jpg)
![2 logo_yellowbg](https://user-images.githubusercontent.com/31815433/30252092-e618b5d8-9689-11e7-99c0-6f54b5b83dce.jpg)
![3 logo_whitebg-1](https://user-images.githubusercontent.com/31815433/30252093-e6243854-9689-11e7-9c89-455e1d2612d7.jpg)
![3 logo_whitebg-2](https://user-images.githubusercontent.com/31815433/30252096-e6636682-9689-11e7-8844-94aad536a5db.jpg)
![3 logo_whitebg](https://user-images.githubusercontent.com/31815433/30252094-e642e222-9689-11e7-87b3-fd001a94bfe2.jpg)

**Comment by healthybee** [comment]
Logo is fixed
